//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHIEVE_TITLE
    {
        public int sIndex { get; set; }
        public string strName { get; set; }
        public Nullable<short> MainID { get; set; }
        public Nullable<short> Str { get; set; }
        public Nullable<short> Hp { get; set; }
        public Nullable<short> Dex { get; set; }
        public Nullable<short> Int { get; set; }
        public Nullable<short> Mp { get; set; }
        public Nullable<short> Attack { get; set; }
        public Nullable<short> Defence { get; set; }
        public Nullable<short> sLoyaltyBonus { get; set; }
        public Nullable<short> sExpBonus { get; set; }
        public Nullable<short> sShortSwordAC { get; set; }
        public Nullable<short> sJamadarAC { get; set; }
        public Nullable<short> sSwordAC { get; set; }
        public Nullable<short> sBlowAC { get; set; }
        public Nullable<short> sAxeAC { get; set; }
        public Nullable<short> sSpearAC { get; set; }
        public Nullable<short> sArrowAC { get; set; }
        public Nullable<short> sFireBonus { get; set; }
        public Nullable<short> sIceBonus { get; set; }
        public Nullable<short> sLightBonus { get; set; }
        public Nullable<short> sFireResist { get; set; }
        public Nullable<short> sIceResist { get; set; }
        public Nullable<short> sLightResist { get; set; }
        public Nullable<short> sMagicResist { get; set; }
        public Nullable<short> sCurseResist { get; set; }
        public Nullable<short> sPoisonResist { get; set; }
    }
}
