//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEGINNER_ITEM
    {
        public Nullable<byte> bIndex { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Class { get; set; }
        public Nullable<byte> Level { get; set; }
        public Nullable<long> Exp { get; set; }
        public Nullable<short> Strong { get; set; }
        public Nullable<short> Dex { get; set; }
        public Nullable<short> Intel { get; set; }
        public Nullable<short> Cha { get; set; }
        public Nullable<short> Sta { get; set; }
        public byte[] Skill { get; set; }
        public Nullable<int> Gold { get; set; }
        public byte[] strItem { get; set; }
        public byte[] strItemBonus { get; set; }
        public byte[] WarehouseData { get; set; }
        public Nullable<int> Loyalty { get; set; }
        public Nullable<short> Points { get; set; }
        public short sQuestCount { get; set; }
        public byte[] strQuest { get; set; }
        public Nullable<byte> KSkillFreePoints { get; set; }
        public Nullable<byte> KSkill1 { get; set; }
        public Nullable<byte> KSkill2 { get; set; }
        public Nullable<byte> KSkill3 { get; set; }
        public Nullable<byte> KMaster { get; set; }
    }
}
