//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLACKLIST
    {
        public string strAccountID { get; set; }
        public string CharID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<long> HardDiskSerial { get; set; }
        public int MACAddress { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
