//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DESTEK
    {
        public int id { get; set; }
        public string StrUserID { get; set; }
        public string StrTitle { get; set; }
        public string StrSoru { get; set; }
        public string StrCevap { get; set; }
        public string StrCatID { get; set; }
        public string StrDurum { get; set; }
    }
}
