//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DESTEKMESAJ
    {
        public int Ticketid { get; set; }
        public string StrUserID { get; set; }
        public string Senduser { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int id { get; set; }
    }
}
