//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_NEWS
    {
        public int id { get; set; }
        public string titletr { get; set; }
        public string titleen { get; set; }
        public string newstr { get; set; }
        public string newsen { get; set; }
        public Nullable<int> tip { get; set; }
        public string tarih { get; set; }
        public string sef { get; set; }
        public Nullable<int> views { get; set; }
        public string link { get; set; }
    }
}
