//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PANELSETTINGS
    {
        public int userdetay { get; set; }
        public string girisyap { get; set; }
        public string kayitol { get; set; }
        public string sifredegistir { get; set; }
        public int siralama_turu { get; set; }
        public string paypal { get; set; }
        public string client_url { get; set; }
    }
}
