//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PUSSETTINGS
    {
        public Nullable<int> NCSCash { get; set; }
        public Nullable<int> NTSCash { get; set; }
        public Nullable<int> PUSStatus { get; set; }
        public Nullable<int> NCSStatus { get; set; }
        public Nullable<int> NTSStatus { get; set; }
        public Nullable<int> ClassCash { get; set; }
        public Nullable<int> ClassStatus { get; set; }
        public int pus_turu { get; set; }
        public long pus_sure { get; set; }
        public int Market { get; set; }
    }
}
