//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SIPARISLER
    {
        public int id { get; set; }
        public string SiparisNo { get; set; }
        public string UrunAdi { get; set; }
        public string Adeti { get; set; }
        public string Fiyati { get; set; }
        public string Durumu { get; set; }
        public string Gonderen { get; set; }
    }
}
