//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_UCRETSIZLOG
    {
        public int id { get; set; }
        public string StrAccountID { get; set; }
        public string SevenTime { get; set; }
        public string StrStatus { get; set; }
        public string EskiNick { get; set; }
        public string YeniNick { get; set; }
        public string EskiIrk { get; set; }
        public string YeniIrk { get; set; }
        public string EskiJob { get; set; }
        public string YeniJob { get; set; }
    }
}
