//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WEBSETTINGS
    {
        public string title { get; set; }
        public string description { get; set; }
        public string keywords { get; set; }
        public string site_path { get; set; }
        public string logo_text { get; set; }
        public string cache_mode { get; set; }
        public int cache_time { get; set; }
        public string lang { get; set; }
        public int online_bugu { get; set; }
    }
}
