//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENTUSER
    {
        public string strAccountID { get; set; }
        public string CharID { get; set; }
        public string ServerIP { get; set; }
        public short ServerPort { get; set; }
        public byte ServerNo { get; set; }
        public string ClientIP { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> HardDiskSerial { get; set; }
        public Nullable<int> MACAddress { get; set; }
        public Nullable<int> slot { get; set; }
    }
}
