//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DROP_MONSTER_ITEMDETAY
    {
        public Nullable<int> classtip { get; set; }
        public Nullable<int> monster_id { get; set; }
        public Nullable<int> image_id { get; set; }
        public string monster_name { get; set; }
        public Nullable<int> monster_hp { get; set; }
        public Nullable<int> monster_defans { get; set; }
        public Nullable<int> monster_atak { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> drop_oran { get; set; }
        public string imagenum { get; set; }
        public string strName { get; set; }
        public string damage { get; set; }
        public string itemtype { get; set; }
        public string kind { get; set; }
        public string Class { get; set; }
        public string atakspeed { get; set; }
        public string Range { get; set; }
        public string Weight { get; set; }
        public string Ac { get; set; }
        public string DaggerAc { get; set; }
        public string SwordAc { get; set; }
        public string MaceAc { get; set; }
        public string AxeAc { get; set; }
        public string SpearAc { get; set; }
        public string BowAc { get; set; }
        public string FireDamage { get; set; }
        public string IceDamage { get; set; }
        public string LightningDamage { get; set; }
        public string PoisonDamage { get; set; }
        public string HPDra { get; set; }
        public string MPDra { get; set; }
        public string MirrorDamage { get; set; }
        public string StrB { get; set; }
        public string StaB { get; set; }
        public string DexB { get; set; }
        public string IntelB { get; set; }
        public string ChaB { get; set; }
        public string MaxHpB { get; set; }
        public string MaxMpB { get; set; }
        public string FireR { get; set; }
        public string ColdR { get; set; }
        public string LightningR { get; set; }
        public string MagicR { get; set; }
        public string PoisonR { get; set; }
        public string CurseR { get; set; }
        public string ReqStr { get; set; }
        public string ReqSta { get; set; }
        public string ReqDex { get; set; }
        public string ReqIntel { get; set; }
        public string ReqCha { get; set; }
        public int id { get; set; }
    }
}
