//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUPE_CHECK
    {
        public int iIndex { get; set; }
        public string strUserID { get; set; }
        public string Name { get; set; }
        public Nullable<int> dwid { get; set; }
        public Nullable<long> strSerial { get; set; }
        public Nullable<int> Durability { get; set; }
        public Nullable<int> StackSize { get; set; }
    }
}
