//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDITOR_LOGS
    {
        public System.DateTime Date { get; set; }
        public string AccountID { get; set; }
        public string TargetAccountID { get; set; }
        public string TargetUserID { get; set; }
        public string ProcessType { get; set; }
        public Nullable<int> KCAmount { get; set; }
        public string OldItem { get; set; }
        public string NewItem { get; set; }
        public string PasswordBefore { get; set; }
        public string PasswordAfter { get; set; }
        public string SealPassBefore { get; set; }
        public string SealPassAfter { get; set; }
    }
}
