//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_SCHEDULER
    {
        public int ID { get; set; }
        public byte ServerNo { get; set; }
        public byte EventType { get; set; }
        public string EventName { get; set; }
        public string EventNote { get; set; }
        public byte nDay { get; set; }
        public byte nHour { get; set; }
        public byte nMinute { get; set; }
        public byte LevelMin { get; set; }
        public byte LevelMax { get; set; }
        public int Extra1 { get; set; }
        public int Extra2 { get; set; }
        public int Extra3 { get; set; }
        public int Extra4 { get; set; }
        public byte Status { get; set; }
    }
}
