//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_CRASH
    {
        public int nIndex { get; set; }
        public byte Flag { get; set; }
        public int ItemID { get; set; }
        public short ItemCount { get; set; }
        public short SuccessRate { get; set; }
    }
}
