//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_SPECIAL_EXCHANGE
    {
        public int nIndex { get; set; }
        public short sNpcID { get; set; }
        public string strName { get; set; }
        public int nReqItemID1 { get; set; }
        public short nReqItemCount1 { get; set; }
        public int nReqItemID2 { get; set; }
        public short nReqItemCount2 { get; set; }
        public int nReqItemID3 { get; set; }
        public short nReqItemCount3 { get; set; }
        public int nReqItemID4 { get; set; }
        public short nReqItemCount4 { get; set; }
        public int nReqItemID5 { get; set; }
        public short nReqItemCount5 { get; set; }
        public int nReqItemID6 { get; set; }
        public short nReqItemCount6 { get; set; }
        public int nReqItemID7 { get; set; }
        public short nReqItemCount7 { get; set; }
        public int nReqItemID8 { get; set; }
        public short nReqItemCount8 { get; set; }
        public int nReqItemID9 { get; set; }
        public short nReqItemCount9 { get; set; }
        public int nReqItemID10 { get; set; }
        public short nReqItemCount10 { get; set; }
        public int nGiveItemID { get; set; }
        public int nGiveItemCount { get; set; }
        public int SuccessRate { get; set; }
    }
}
