//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_EXCHANGE_EXP
    {
        public int nIndex { get; set; }
        public byte bRandomFlag { get; set; }
        public long nExchangeItemNum1 { get; set; }
        public int nExchangeItemCount1 { get; set; }
        public long nExchangeItemNum2 { get; set; }
        public int nExchangeItemCount2 { get; set; }
        public long nExchangeItemNum3 { get; set; }
        public int nExchangeItemCount3 { get; set; }
        public long nExchangeItemNum4 { get; set; }
        public int nExchangeItemCount4 { get; set; }
        public long nExchangeItemNum5 { get; set; }
        public int nExchangeItemCount5 { get; set; }
    }
}
