//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_FISHING_LIST
    {
        public short sIndex { get; set; }
        public int Num { get; set; }
        public string strName { get; set; }
        public short sRateNormal { get; set; }
        public Nullable<short> sRateGolden { get; set; }
    }
}
