//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_EXCHANGE
    {
        public int nIndex { get; set; }
        public byte bRandomFlag { get; set; }
        public long ExchangeType { get; set; }
        public long nOriginItemNum1 { get; set; }
        public int nOriginItemCount1 { get; set; }
        public long nOriginItemNum2 { get; set; }
        public int nOriginItemCount2 { get; set; }
        public long nOriginItemNum3 { get; set; }
        public int nOriginItemCount3 { get; set; }
        public long nOriginItemNum4 { get; set; }
        public int nOriginItemCount4 { get; set; }
        public long nOriginItemNum5 { get; set; }
        public int nOriginItemCount5 { get; set; }
        public long nExchangeItemNum1 { get; set; }
        public int nExchangeItemCount1 { get; set; }
        public long nExchangeItemNum2 { get; set; }
        public int nExchangeItemCount2 { get; set; }
        public long nExchangeItemNum3 { get; set; }
        public int nExchangeItemCount3 { get; set; }
        public long nExchangeItemNum4 { get; set; }
        public int nExchangeItemCount4 { get; set; }
        public long nExchangeItemNum5 { get; set; }
        public int nExchangeItemCount5 { get; set; }
        public long unknown1 { get; set; }
        public long unknown11 { get; set; }
        public string unknown12 { get; set; }
    }
}
