//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KING_NOMINATION_LIST
    {
        public byte Nation { get; set; }
        public string strNominee { get; set; }
        public string strNominator { get; set; }
        public System.DateTime Date { get; set; }
    }
}
