//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNIGHTS
    {
        public short IDNum { get; set; }
        public string IDName { get; set; }
        public byte Flag { get; set; }
        public byte Nation { get; set; }
        public byte Ranking { get; set; }
        public long Gold { get; set; }
        public short Domination { get; set; }
        public byte[] Mark { get; set; }
        public short sMarkVersion { get; set; }
        public short sMarkLen { get; set; }
        public short sCape { get; set; }
        public byte bCapeR { get; set; }
        public byte bCapeG { get; set; }
        public byte bCapeB { get; set; }
        public short sAllianceKnights { get; set; }
        public Nullable<int> ClanPointFund { get; set; }
        public string strClanNotice { get; set; }
        public byte ClanPointMethod { get; set; }
        public System.DateTime dtCreateTime { get; set; }
        public Nullable<byte> bySiegeFlag { get; set; }
        public int ClanPremiumTime { get; set; }
        public int ClanPreFinishTime { get; set; }
        public Nullable<short> nLose { get; set; }
        public Nullable<short> nVictory { get; set; }
        public Nullable<short> Members { get; set; }
        public string Chief { get; set; }
        public string ViceChief_1 { get; set; }
        public string ViceChief_2 { get; set; }
        public string ViceChief_3 { get; set; }
        public int Points { get; set; }
    }
}
