//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNIGHTS_ALLIANCE
    {
        public short sMainAllianceKnights { get; set; }
        public short sSubAllianceKnights { get; set; }
        public short sMercenaryClan_1 { get; set; }
        public short sMercenaryClan_2 { get; set; }
    }
}
