//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAGIC
    {
        public int MagicNum { get; set; }
        public string EnName { get; set; }
        public string KrName { get; set; }
        public string Description { get; set; }
        public Nullable<int> BeforeAction { get; set; }
        public Nullable<byte> TargetAction { get; set; }
        public Nullable<byte> SelfEffect { get; set; }
        public Nullable<short> FlyingEffect { get; set; }
        public Nullable<int> TargetEffect { get; set; }
        public Nullable<byte> Moral { get; set; }
        public Nullable<short> SkillLevel { get; set; }
        public Nullable<short> Skill { get; set; }
        public Nullable<short> Msp { get; set; }
        public Nullable<short> HP { get; set; }
        public Nullable<short> Stamina { get; set; }
        public Nullable<byte> ItemGroup { get; set; }
        public Nullable<int> UseItem { get; set; }
        public Nullable<short> CastTime { get; set; }
        public Nullable<short> ReCastTime { get; set; }
        public Nullable<short> SuccessRate { get; set; }
        public Nullable<byte> Type1 { get; set; }
        public Nullable<byte> Type2 { get; set; }
        public Nullable<short> Range { get; set; }
        public Nullable<byte> UseStanding { get; set; }
        public Nullable<short> Etc { get; set; }
        public byte IsCasting { get; set; }
        public string test1 { get; set; }
    }
}
