//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAGIC_TYPE1
    {
        public int iNum { get; set; }
        public byte Type { get; set; }
        public short HitRate { get; set; }
        public short Hit { get; set; }
        public Nullable<short> AddDamage { get; set; }
        public byte Delay { get; set; }
        public byte ComboType { get; set; }
        public byte ComboCount { get; set; }
        public short ComboDamage { get; set; }
        public short Range { get; set; }
    }
}
