//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MALL_LIST
    {
        public int sIndex { get; set; }
        public string view_type { get; set; }
        public int view_rank { get; set; }
        public string goodsno { get; set; }
        public string name { get; set; }
        public string smallimage { get; set; }
        public string bigimage { get; set; }
        public string mainicon { get; set; }
        public string subicon { get; set; }
        public int price { get; set; }
        public int event_price { get; set; }
        public int dtype { get; set; }
        public int buytype { get; set; }
        public int invencnt { get; set; }
        public string explain1 { get; set; }
        public string explain2 { get; set; }
        public int item_type { get; set; }
        public int limit_type { get; set; }
        public int limit_total { get; set; }
        public int limit_remain { get; set; }
        public System.DateTime limit_sdate { get; set; }
        public System.DateTime limit_edate { get; set; }
        public int limit_age { get; set; }
        public int issue_check { get; set; }
        public string issue_image { get; set; }
        public int char_sex { get; set; }
        public string item_property { get; set; }
        public int addhour { get; set; }
        public int sellCount { get; set; }
    }
}
