//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kn_onlineEntities2 : DbContext
    {
        public kn_onlineEntities2()
            : base("name=kn_onlineEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_DESTEK> C_DESTEK { get; set; }
        public virtual DbSet<C_DESTEKMESAJ> C_DESTEKMESAJ { get; set; }
        public virtual DbSet<ITEM_EXCHANGE_ITEMDETAY> ITEM_EXCHANGE_ITEMDETAY { get; set; }
        public virtual DbSet<LEVEL_UP> LEVEL_UP { get; set; }
        public virtual DbSet<USERDATA> USERDATA { get; set; }
        public virtual DbSet<C_BANKALAR> C_BANKALAR { get; set; }
        public virtual DbSet<C_BLOCK> C_BLOCK { get; set; }
        public virtual DbSet<C_CASHPAKETI> C_CASHPAKETI { get; set; }
        public virtual DbSet<C_CODEHISTORY> C_CODEHISTORY { get; set; }
        public virtual DbSet<C_DOWNLOADS> C_DOWNLOADS { get; set; }
        public virtual DbSet<C_LINKS> C_LINKS { get; set; }
        public virtual DbSet<C_MENU> C_MENU { get; set; }
        public virtual DbSet<C_NEWS> C_NEWS { get; set; }
        public virtual DbSet<C_PANELSETTINGS> C_PANELSETTINGS { get; set; }
        public virtual DbSet<C_PAYMENTNOTICE> C_PAYMENTNOTICE { get; set; }
        public virtual DbSet<C_POLLS> C_POLLS { get; set; }
        public virtual DbSet<C_PUSSETTINGS> C_PUSSETTINGS { get; set; }
        public virtual DbSet<C_SIPARISLER> C_SIPARISLER { get; set; }
        public virtual DbSet<C_SOCIAL> C_SOCIAL { get; set; }
        public virtual DbSet<C_UCRETSIZLOG> C_UCRETSIZLOG { get; set; }
        public virtual DbSet<C_VOTES> C_VOTES { get; set; }
        public virtual DbSet<C_WEBSETTINGS> C_WEBSETTINGS { get; set; }
        public virtual DbSet<ACCOUNT_CHAR> ACCOUNT_CHAR { get; set; }
        public virtual DbSet<CURRENTUSER> CURRENTUSER { get; set; }
        public virtual DbSet<KNIGHTS> KNIGHTS { get; set; }
        public virtual DbSet<USER_ITEM_INFO> USER_ITEM_INFO { get; set; }
        public virtual DbSet<DROP_MONSTER_ITEMDETAY> DROP_MONSTER_ITEMDETAY { get; set; }
        public virtual DbSet<TB_USER> TB_USER { get; set; }
    }
}
