//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETDATA
    {
        public short ID { get; set; }
        public short sSid { get; set; }
        public short sPid { get; set; }
        public string strName { get; set; }
        public short strClass { get; set; }
        public byte strLevel { get; set; }
        public long strExp { get; set; }
        public short strHp { get; set; }
        public short strMp { get; set; }
        public short strSatisFaction { get; set; }
        public long strPetSarial { get; set; }
        public byte[] StrItem { get; set; }
        public byte[] strItemEx { get; set; }
        public byte[] StrSarial { get; set; }
    }
}
