//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREMIUM_ITEM_GIFT
    {
        public byte bIndex { get; set; }
        public byte bType { get; set; }
        public int nItemID { get; set; }
        public string strItemName { get; set; }
        public short sCount { get; set; }
        public short sDurability { get; set; }
        public int CashPoints { get; set; }
    }
}
