//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREMIUM_SERVICE_USER
    {
        public string strAccountID { get; set; }
        public Nullable<byte> bUsePremium { get; set; }
        public Nullable<byte> PremType0 { get; set; }
        public Nullable<System.DateTime> PremTime0 { get; set; }
        public Nullable<byte> PremType1 { get; set; }
        public Nullable<System.DateTime> PremTime1 { get; set; }
        public Nullable<byte> PremType2 { get; set; }
        public Nullable<System.DateTime> PremTime2 { get; set; }
        public Nullable<byte> PremType3 { get; set; }
        public Nullable<System.DateTime> PremTime3 { get; set; }
        public Nullable<byte> PremType4 { get; set; }
        public Nullable<System.DateTime> PremTime4 { get; set; }
    }
}
