//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUS_SESSIONS
    {
        public int ID { get; set; }
        public string strAccountID { get; set; }
        public string strCharID { get; set; }
        public string strClass { get; set; }
        public Nullable<byte> nLevel { get; set; }
        public Nullable<byte> FreeSlotCount { get; set; }
        public string SessionKey { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
