//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEND_MESSAGES
    {
        public int id { get; set; }
        public string strMessage { get; set; }
        public string strSender { get; set; }
        public short bChatType { get; set; }
        public short SendType { get; set; }
        public short SendHourMinute { get; set; }
    }
}
