//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVER_LIST
    {
        public int sServerID { get; set; }
        public int sGroupID { get; set; }
        public string strServerName { get; set; }
        public string strServerIP { get; set; }
        public string strLanIP { get; set; }
        public int sPlayerCap { get; set; }
        public int sFreePlayerCap { get; set; }
        public string strKarusKingName { get; set; }
        public string strKarusNotice { get; set; }
        public string strElMoradKingName { get; set; }
        public string strElMoradNotice { get; set; }
    }
}
