//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class TB_USER
    {
        [Required(ErrorMessage = "Kullanýcý Adý alaný boþ geçilemez!")]
        [StringLength(10, ErrorMessage = "Kullanýcý Adý alaný en fazla {1}, en az 4 karakter uzunluðunda olmalýdýr!", MinimumLength = 4)]
        public string strAccountID { get; set; }

        [Required(ErrorMessage = "Parola alaný boþ geçilemez!")]
        [StringLength(10, ErrorMessage = "Parola alaný en fazla {1}, en az 4 karakter uzunluðunda olmalýdýr!", MinimumLength = 4)]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public byte bAuthority { get; set; }
        public string IPAddress { get; set; }
        public string CountryCode { get; set; }
        public int HardDiskSerial { get; set; }
        public int MACAddress { get; set; }
        [StringLength(25, ErrorMessage = "Email alaný en fazla {1} karakter uzunluðunda olmalýdýr!")]
        [Required(ErrorMessage = "Email alaný gereklidir!")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                        @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                        @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                        ErrorMessage = "Email adresi geçersiz!")]
        public string Email { get; set; }
        public byte SecretQuestionID { get; set; }
        public string SecretQuestionAnswer { get; set; }
        [StringLength(8, ErrorMessage = "Eþya Kilit alaný en fazla {1}, en az 4 karakter uzunluðunda olmalýdýr!", MinimumLength = 4)]
        public string SealPassword { get; set; }
        public string EmailNew { get; set; }
        public string AuthCode { get; set; }
        public Nullable<System.DateTime> AuthCodeTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<byte> bPremiumType { get; set; }
        public Nullable<System.DateTime> dtPremiumTime { get; set; }
        public Nullable<byte> bDeveloper { get; set; }
        public Nullable<byte> bLogin { get; set; }
        public Nullable<System.DateTime> dtNationChange { get; set; }
        public Nullable<byte> PanelAdmin { get; set; }
        public string VipKey { get; set; }
        [Required(ErrorMessage = "Telefon Numarasý alaný boþ geçilemez!")]
        [StringLength(15, ErrorMessage = "Telefon Numarasý alaný en fazla {1}, en az 11 karakter uzunluðunda olmalýdýr!", MinimumLength = 11)]
        public string Phone { get; set; }
        public byte EnableOtp { get; set; }
        public string OtpSecret { get; set; }
        public string OtpPass { get; set; }
        public string OtpQrUrl { get; set; }
        public string OtpManualKey { get; set; }
        public byte OtpAuth { get; set; }
        public byte strAuthority { get; set; }
        public Nullable<System.DateTime> PunishmentDate { get; set; }
        public Nullable<byte> PunishmentPeriod { get; set; }
        public int id { get; set; }
        [Compare("Password", ErrorMessage = "Ýki þifre eþleþmiyor!")]
        [DataType(DataType.Password)]
        public string Sifre { get; set; }
    }
}
