//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER_PREMIUM
    {
        public string strAccountID { get; set; }
        public byte bPremiumType { get; set; }
        public System.DateTime dtPremiumTime { get; set; }
    }
}
