//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER
    {
        public string strAccountID { get; set; }
        public string Password { get; set; }
        public byte bAuthority { get; set; }
        public string IPAddress { get; set; }
        public string CountryCode { get; set; }
        public int HardDiskSerial { get; set; }
        public int MACAddress { get; set; }
        public string Email { get; set; }
        public byte SecretQuestionID { get; set; }
        public string SecretQuestionAnswer { get; set; }
        public string SealPassword { get; set; }
        public string EmailNew { get; set; }
        public string AuthCode { get; set; }
        public Nullable<System.DateTime> AuthCodeTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<byte> bPremiumType { get; set; }
        public Nullable<System.DateTime> dtPremiumTime { get; set; }
        public Nullable<byte> bDeveloper { get; set; }
        public Nullable<byte> bLogin { get; set; }
        public Nullable<System.DateTime> dtNationChange { get; set; }
        public Nullable<byte> PanelAdmin { get; set; }
        public string VipKey { get; set; }
        public string Phone { get; set; }
        public byte EnableOtp { get; set; }
        public string OtpSecret { get; set; }
        public string OtpPass { get; set; }
        public string OtpQrUrl { get; set; }
        public string OtpManualKey { get; set; }
        public byte OtpAuth { get; set; }
        public byte strAuthority { get; set; }
        public Nullable<System.DateTime> PunishmentDate { get; set; }
        public Nullable<byte> PunishmentPeriod { get; set; }
        public int id { get; set; }
        public string Sifre { get; set; }
    }
}
