//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFORGOTPASSW
    {
        public string strAccountID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> INSDATE { get; set; }
        public string GUID { get; set; }
        public string TIP { get; set; }
        public string ISLEM { get; set; }
        public int id { get; set; }
    }
}
