//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_KNIGHTS_RANK
    {
        public short shIndex { get; set; }
        public string strName { get; set; }
        public string strElmoUserID { get; set; }
        public string strElmoKnightsName { get; set; }
        public Nullable<short> sElmoKnights { get; set; }
        public Nullable<int> nElmoLoyalty { get; set; }
        public string strKarusUserID { get; set; }
        public string strKarusKnightsName { get; set; }
        public Nullable<short> sKarusKnights { get; set; }
        public Nullable<int> nKarusLoyalty { get; set; }
        public int nMoney { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
