//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ITEM_INFO
    {
        public string itemnum { get; set; }
        public Nullable<short> stacksize { get; set; }
        public Nullable<short> durability { get; set; }
        public string strUserId { get; set; }
        public Nullable<int> sira { get; set; }
        public string itembasicname { get; set; }
        public string extname { get; set; }
        public int id { get; set; }
        public string kind { get; set; }
        public string itemtype { get; set; }
        public string Class { get; set; }

    }
}
