//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SAVED_MAGIC
    {
        public string strCharID { get; set; }
        public int nSkillID1 { get; set; }
        public int nExpiry1 { get; set; }
        public int nSkillID2 { get; set; }
        public int nExpiry2 { get; set; }
        public int nSkillID3 { get; set; }
        public int nExpiry3 { get; set; }
        public int nSkillID4 { get; set; }
        public int nExpiry4 { get; set; }
        public int nSkillID5 { get; set; }
        public int nExpiry5 { get; set; }
        public int nSkillID6 { get; set; }
        public int nExpiry6 { get; set; }
        public int nSkillID7 { get; set; }
        public int nExpiry7 { get; set; }
        public int nSkillID8 { get; set; }
        public int nExpiry8 { get; set; }
        public int nSkillID9 { get; set; }
        public int nExpiry9 { get; set; }
        public int nSkillID10 { get; set; }
        public int nExpiry10 { get; set; }
    }
}
