//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ACHIEVE_DATA
    {
        public string strUserID { get; set; }
        public short sCoverID { get; set; }
        public short sSkillID { get; set; }
        public short sAchieveCount { get; set; }
        public byte[] strAchieve { get; set; }
    }
}
