//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERDATA
    {
        public string strUserID { get; set; }
        public byte Race { get; set; }
        public short Class { get; set; }
        public int HairRGB { get; set; }
        public byte Rank { get; set; }
        public byte Title { get; set; }
        public byte Face { get; set; }
        public int Gold { get; set; }
        public byte City { get; set; }
        public int dwTime { get; set; }
        public System.DateTime dtCreateTime { get; set; }
        public Nullable<System.DateTime> dtUpdateTime { get; set; }
        public byte bFirstLogin { get; set; }
        public byte DrakiRegisterCount { get; set; }
        public int LastOnline { get; set; }
        public int DrakiLastUpdate { get; set; }
        public byte isReturnee { get; set; }
        public Nullable<byte> Nation { get; set; }
        public Nullable<short> Knights { get; set; }
        public byte[] strItem { get; set; }
        public byte[] strItemEx { get; set; }
        public byte[] strItemFlag { get; set; }
        public byte[] strSerial { get; set; }
        public byte[] strDeletedItem { get; set; }
        public byte Level { get; set; }
        public byte RebirthLevel { get; set; }
        public long Exp { get; set; }
        public int Loyalty { get; set; }
        public int LoyaltyMonthly { get; set; }
        public int MannerPoint { get; set; }
        public byte Authority { get; set; }
        public Nullable<int> sTimePunishment { get; set; }
        public Nullable<System.DateTime> dtPunishDate { get; set; }
        public byte[] strPermission { get; set; }
        public short Hp { get; set; }
        public short Mp { get; set; }
        public short Sp { get; set; }
        public byte Strong { get; set; }
        public byte Sta { get; set; }
        public byte Dex { get; set; }
        public byte Intel { get; set; }
        public byte Cha { get; set; }
        public short Points { get; set; }
        public byte RebStrong { get; set; }
        public byte RebSta { get; set; }
        public byte RebDex { get; set; }
        public byte RebIntel { get; set; }
        public byte RebCha { get; set; }
        public byte[] strSkill { get; set; }
        public byte Zone { get; set; }
        public Nullable<short> Bind { get; set; }
        public int PX { get; set; }
        public int PZ { get; set; }
        public int PY { get; set; }
        public int GenieRemaining { get; set; }
        public byte[] strGenieOptions { get; set; }
        public short sQuestCount { get; set; }
        public byte[] strQuest { get; set; }
        public short ClanID { get; set; }
        public byte Fame { get; set; }
        public int nDonatedNP { get; set; }
        public string strMemo { get; set; }
        public Nullable<int> LastLogin { get; set; }
        public string Description { get; set; }
        public int id { get; set; }
    }
}
