//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIP_WAREHOUSE
    {
        public string strAccountID { get; set; }
        public string strPassword { get; set; }
        public int iExpirationDate { get; set; }
        public byte[] VIPWarehouseData { get; set; }
        public byte[] strSerial { get; set; }
    }
}
