//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAITING_COMMANDS
    {
        public long nIndex { get; set; }
        public string strCommand { get; set; }
        public Nullable<byte> bState { get; set; }
        public string strResponse { get; set; }
        public Nullable<System.DateTime> tDate { get; set; }
    }
}
