//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KO_Fenix.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHEEL_OF_FUN_LOG
    {
        public int ID { get; set; }
        public string Date { get; set; }
        public string ItemName { get; set; }
        public string NPoints { get; set; }
        public string UserName { get; set; }
    }
}
